import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import {spawn,spawnSync} from 'node:child_process'
import {readEDN,writeEDN,keyword as k} from './edn.mjs'
import {context,readDocument,listDocuments,mutateDocument,query,readChanges,revision,MAX_EVENTS,rawBound} from '../../tools/world-data.mjs'
import {options,execute as map,ttl} from '../../tools/map.mjs'
import {options as changeOptions,execute as changes} from '../../tools/world-changes.mjs'
const root=path.resolve(import.meta.dirname,'../../..')
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'agent-world-'));fs.mkdirSync(`${dir}/worlds/test`,{recursive:true});fs.writeFileSync(`${dir}/worlds/test/world.json`,'{}');fs.mkdirSync(`${dir}/blueprints`);t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return {dir,ctx:context({state:dir,world:'test',repoRoot:dir}),args:['--state',dir,'--world','test','--repo-root',dir]}}
const marker=(id,x=0,by='Alice')=>({name:id,kind:'base',x,y:64,z:0,by,note:'',source:'intent'})
async function add(ctx,id,x=0){return mutateDocument(ctx,{kind:'marker',id,expectedRevision:null,value:marker(id,x),by:'Alice'})}
test('existing storage paths, global blueprint scope, revisions and unknown fields round-trip',async t=>{const {ctx}=fixture(t);fs.writeFileSync(`${ctx.worldDir}/places.json`,JSON.stringify([{...marker('legacy place'),structure:{legend:{'#':'stone'},layers:[['#']]},unknown:'preserved'}]));const d=readDocument(ctx,'marker','legacy place');assert.equal(d.value.unknown,'preserved');assert.equal(d.value.structure.legend['#'],'stone');assert.equal(d.revision,revision(JSON.stringify(d.value)));const b=await mutateDocument(ctx,{kind:'blueprint',id:'hut',expectedRevision:null,value:{id:'hut',parts:[]},by:'Alice'});assert.equal(b.scope.key,'global');assert.equal(readDocument(ctx,'blueprint','hut').value.id,'hut');assert.throws(()=>readDocument(ctx,'plan','../escape'),{reason:'invalid-id'})})
test('CAS create/edit/remove, concurrent collisions, external edit detection, dry-run',async t=>{const {ctx}=fixture(t);const a=await add(ctx,'home');await assert.rejects(add(ctx,'home'),{reason:'revision-conflict'});const previous=readDocument(ctx,'marker','home');const updates=await Promise.allSettled([1,2].map(x=>mutateDocument(ctx,{kind:'marker',id:'home',expectedRevision:a.revision,value:marker('home',x),by:'Alice'})));assert.equal(updates.filter(r=>r.status==='fulfilled').length,1);assert.equal(updates.filter(r=>r.status==='rejected'&&r.reason.reason==='revision-conflict').length,1);const now=readDocument(ctx,'marker','home');const before=fs.readFileSync(now.path,'utf8');const preview=await mutateDocument(ctx,{kind:'marker',id:'home',expectedRevision:now.revision,value:{...now.value,note:'preview'},by:'Alice',dryRun:true});assert.equal(preview.preview,true);assert.deepEqual(preview.fields,['note']);assert.equal(fs.readFileSync(now.path,'utf8'),before);fs.writeFileSync(now.path,JSON.stringify([marker('home',40)]));await assert.rejects(mutateDocument(ctx,{kind:'marker',id:'home',expectedRevision:now.revision,value:null,by:'Alice'}),{reason:'revision-conflict'});const latest=readDocument(ctx,'marker','home');await mutateDocument(ctx,{kind:'marker',id:'home',expectedRevision:latest.revision,value:null,by:'Alice'});assert.equal(readDocument(ctx,'marker','home'),null);assert.notEqual(previous.revision,latest.revision)})
test('query needs no body and uses explicit spatial center, exact owner/status, finite pagination',t=>{fixture(t);const rows=[0,50,500].map((x,i)=>({kind:'marker',id:`p${i}`,value:marker(`p${i}`,x),revision:'rev',scope:'world'}));assert.equal(query(rows).total,3);const page=query(rows,{center:[0,64,0],limit:1});assert.equal(page.total,2);assert.equal(page['next-offset'],1);assert.equal(page.items[0].id,'p0');assert.equal(query(rows,{center:[0,64,0],offset:1}).items[0].id,'p1');assert.equal(query(rows,{owner:'alice',type:'base'}).total,3);assert.throws(()=>query(rows,{limit:101}),{reason:'invalid-page'});assert.throws(()=>query(rows,{center:[0]}),{reason:'invalid-center'});assert.throws(()=>rawBound({huge:'x'.repeat(70000)}),{reason:'output-too-large'})})
test('world changes distinguish authored/external writes, paginate without losing interleaved objects and disclose gaps',async t=>{const {ctx}=fixture(t);const initial=await readChanges(ctx);await add(ctx,'a');await add(ctx,'b');const a=readDocument(ctx,'marker','a');await mutateDocument(ctx,{kind:'marker',id:'a',expectedRevision:a.revision,value:marker('a',3),by:'Alice'});let first=await readChanges(ctx,{cursor:initial.cursor,limit:1});assert.equal(first.items.length,1);assert.equal(first.items[0].id,'a');assert.equal(first.items[0].source.key,'intent');assert.equal(first['more?'],true);let second=await readChanges(ctx,{cursor:first.cursor,limit:1});assert.equal(second.items[0].id,'b');let third=await readChanges(ctx,{cursor:second.cursor,limit:1});assert.equal(third.items[0].id,'a');assert.equal(third.items[0].op.key,'edit');fs.writeFileSync(`${ctx.worldDir}/places.json`,JSON.stringify([marker('a',4),marker('b')]));const external=await readChanges(ctx,{cursor:third.cursor});assert.equal(external.items[0].source.key,'external');assert.equal((await readChanges(ctx,{cursor:{stream:'wrong',seq:0}})).reason.key,'cursor-gap');const file=`${ctx.metadataDir}/changes.edn`,ledger=readEDN(fs.readFileSync(file,'utf8'));ledger.seq=5000;ledger.events=Array.from({length:MAX_EVENTS},(_,i)=>({seq:5000-MAX_EVENTS+i+1,kind:'marker',id:'a',scope:'world',op:'edit',source:'intent'}));fs.writeFileSync(file,writeEDN(ledger));const gap=await readChanges(ctx,{cursor:initial.cursor});assert.equal(gap.reason.key,'cursor-gap');assert.equal(gap['oldest-seq'],5000-MAX_EVENTS+1)})
test('validation fails before persistence and required actor/revisions prevent ambiguous writes',async t=>{const {ctx}=fixture(t);await assert.rejects(mutateDocument(ctx,{kind:'plan',id:'p',expectedRevision:null,value:{id:'p'},by:'Alice',validate:()=>({errors:['bad plan']})}),{reason:'validation'});assert.equal(readDocument(ctx,'plan','p'),null);await assert.rejects(mutateDocument(ctx,{kind:'marker',id:'x',value:marker('x'),by:'Alice'}),{reason:'revision-required'});await assert.rejects(mutateDocument(ctx,{kind:'marker',id:'x',expectedRevision:null,value:marker('x')}),{reason:'actor-required'})})
test('claim lifecycle, overlap collision and ownership are separate from engine zones',async t=>{const {ctx,args}=fixture(t);const data=writeEDN({min:[0,60,0],max:[5,70,5]});const a=await map(options([...args,'add','claim','claim-a','--data',data,'--by','Alice','--for','500ms']));assert.equal(readDocument(ctx,'claim','claim-a').value.owner,'Alice');assert.equal(readDocument(ctx,'zone','claim-a'),null);await assert.rejects(map(options([...args,'add','claim','claim-b','--data',data,'--by','Bob'])),{reason:'claim-conflict'});await assert.rejects(map(options([...args,'release','claim','claim-a','--revision',a.revision,'--by','Bob'])),{reason:'not-owner'});const renewed=await map(options([...args,'renew','claim','claim-a','--revision',a.revision,'--by','Alice','--for','1h']));assert.ok(readDocument(ctx,'claim','claim-a').value.until>Date.now()+3500000);const released=await map(options([...args,'release','claim','claim-a','--revision',renewed.revision,'--by','Alice']));assert.equal((await map(options([...args,'find','--type','claim']))).total,0);assert.equal((await map(options([...args,'show','claim','claim-a']))).status.key,'released');await map(options([...args,'add','claim','claim-b','--data',data,'--by','Bob']));assert.ok(released.revision);assert.throws(()=>ttl('8d'),{reason:'invalid-duration'})})
test('marker edit preserves ownership/structure, note-only collaboration, canonical strict zone schema',async t=>{const {ctx,args}=fixture(t);fs.writeFileSync(`${ctx.worldDir}/places.json`,JSON.stringify([{...marker('home'),structure:{layers:[['stone']]}}]));let d=readDocument(ctx,'marker','home');const note=await map(options([...args,'edit','marker','home','--revision',d.revision,'--by','Bob','--data','{:note "hello"}']));d=readDocument(ctx,'marker','home');assert.equal(d.value.by,'Alice');assert.deepEqual(d.value.structure,{layers:[['stone']]});await assert.rejects(map(options([...args,'edit','marker','home','--revision',note.revision,'--by','Bob','--data','{:x 20}'])),{reason:'not-owner'});await assert.rejects(map(options([...args,'remove','marker','home','--revision',note.revision,'--by','Bob'])),{reason:'not-owner'});const z=await map(options([...args,'add','zone','safe','--by','Alice','--data','{:min [0 60 0] :max [10 70 10] :allow #{:harvest}}']));assert.equal(fs.existsSync(`${ctx.worldDir}/zones.edn`),true);assert.equal(fs.existsSync(`${ctx.worldDir}/zones.json`),false);assert.deepEqual(readDocument(ctx,'zone','safe').value.allow,{set:[k('harvest')]});await assert.rejects(map(options([...args,'edit','zone','safe','--by','Alice','--revision',z.revision,'--data','{:revision 3}'])),{reason:'validation'})})
test('raw map mutations return bounded proposed/current/removed records and mark truncated notes',async t=>{const {ctx,args}=fixture(t),longNote='n'.repeat(300),data=value=>writeEDN({min:[0,60,0],max:[1,70,1],note:value});const added=await map(options([...args,'add','zone','raw-zone','--by','Alice','--data',data(longNote),'--raw']));assert.equal(added.record.note,longNote);const found=await map(options([...args,'find','--type','zone','--raw']));assert.equal(found.items[0]['note-truncated?'],true);assert.equal(found.items[0].note.length,240);assert.equal(found.items[0].record.note,longNote);const preview=await map(options([...args,'edit','zone','raw-zone','--by','Alice','--revision',added.revision,'--data',data('proposal'),'--dry-run','--raw']));assert.equal(preview.preview,true);assert.equal(preview.record.note,'proposal');assert.equal(readDocument(ctx,'zone','raw-zone').value.note,longNote);const removed=await map(options([...args,'remove','zone','raw-zone','--by','Alice','--revision',added.revision,'--raw']));assert.equal(removed.record.note,longNote);assert.equal(readDocument(ctx,'zone','raw-zone'),null);const tooLarge='x'.repeat(65470);await assert.rejects(map(options([...args,'add','zone','too-large','--by','Alice','--data',data(tooLarge),'--raw'])),{reason:'output-too-large'});assert.equal(readDocument(ctx,'zone','too-large'),null)})
test('claim overlap errors page summaries and give a spatial query for remaining claims',async t=>{const {ctx,args}=fixture(t),until=Date.now()+3600000,claims=Array.from({length:12},(_,i)=>({id:`old-${i}`,owner:`Owner${i}`,min:[0,60,0],max:[5,70,5],until,status:k('active')}));fs.writeFileSync(`${ctx.worldDir}/claims.edn`,writeEDN(claims));const argv=[...args,'add','claim','new','--by','Alice','--data',writeEDN({min:[1,60,1],max:[2,70,2]})];await assert.rejects(map(options(argv)),error=>{assert.equal(error.reason,'claim-conflict');assert.equal(error.conflicts.length,12);assert.equal(error['conflicts-total'],12);assert.equal(error['more?'],true);assert.match(error.next,/find --type claim --status active --center/);return true});const result=spawnSync('node',[`${root}/engine/tools/map.mjs`,...argv],{encoding:'utf8'});assert.equal(result.error,undefined);const error=readEDN(result.stdout.trim());assert.equal(result.status,1);assert.equal(error['conflicts-total'],12);assert.equal(error['more?'],true);assert.equal(error.conflicts.length,10);assert.match(error.next,/--radius/)})
test('CLI end-to-end runs on isolated world without a body; raw is full scoped data and errors do not mutate',t=>{const {dir,args}=fixture(t);const run=argv=>{const result=spawnSync('node',[`${root}/engine/tools/map.mjs`,...args,...argv],{encoding:'utf8'});assert.equal(result.error,undefined);return result};const added=run(['add','marker','base','--by','Alice','--data','{:kind "base" :x 1 :y 64 :z 2}']);assert.equal(added.status,0,added.stdout+added.stderr);const raw=readEDN(run(['show','marker','base','--raw']).stdout);assert.equal(raw.record.x,1);assert.equal(raw.record.by,'Alice');assert.equal('path' in raw,false);assert.equal('text' in raw,false);const find=readEDN(run(['find','--place','base']).stdout);assert.equal(find.items[0].distance,0);assert.equal(run(['edit','marker','base','--by','Alice','--data','{:note "bad"}']).status,1);assert.equal(run(['find','--radius','10']).status,1);assert.equal(fs.existsSync(`${dir}/worlds/test/agents`),false)})
test('named change observer waits, filters, timeout, cancellation and concurrent exclusion',async t=>{const {ctx,args}=fixture(t);let out;const wait=changeOptions([...args,'--wait','--timeout','500ms','--poll-ms','50','--observer','test','--type','marker']);const promise=changes(wait,{output:async x=>{out=x}});await new Promise(r=>setTimeout(r,70));await assert.rejects(changes(wait,{output:async()=>{}}),{reason:'busy'});await add(ctx,'wake');await promise;assert.equal(out.items[0].id,'wake');const quiet=await changes(changeOptions([...args,'--wait','--timeout','100ms','--poll-ms','50','--observer','test']),{output:async()=>{}});assert.equal(quiet.timeout,true);assert.equal(quiet.items.length,0);const controller=new AbortController();const cancelled=changes(changeOptions([...args,'--wait','--timeout','500ms','--observer','cancel']),{signal:controller.signal,output:async()=>{throw Error('should not print')}});await new Promise(r=>setTimeout(r,50));controller.abort();await assert.rejects(cancelled);await add(ctx,'after-cancel');const resumed=await changes(changeOptions([...args,'--observer','cancel']),{output:async()=>{}});assert.equal(resumed.items[0].id,'after-cancel')})
test('global blueprint pending recovery precedes another world mutation and commits original ledger once',async t=>{const {ctx,dir}=fixture(t);fs.mkdirSync(`${dir}/worlds/other`);fs.writeFileSync(`${dir}/worlds/other/world.json`,'{}');const other=context({state:dir,world:'other',repoRoot:dir});const a=await mutateDocument(ctx,{kind:'blueprint',id:'hut',expectedRevision:null,value:{id:'hut',note:'before'},by:'Alice'});const file=readDocument(ctx,'blueprint','hut').path,after=writeEDN({id:'hut',note:'interrupted'})+'\n';const ledger=readEDN(fs.readFileSync(`${ctx.metadataDir}/changes.edn`,'utf8'));const pendingEvent={seq:++ledger.seq,kind:'blueprint',id:'hut',scope:'global',revision:revision(after),op:'edit',source:'intent',by:'Alice'};ledger.events.push(pendingEvent);ledger.index['blueprint/hut']={...ledger.index['blueprint/hut'],revision:revision(after)};const journal={context:{state:dir,world:'test',repoRoot:dir},file,kind:'blueprint',id:'hut',before:a.revision,after,ledger};fs.writeFileSync(`${ctx.blueprintDir}/.agent-pending.edn`,writeEDN(journal));fs.writeFileSync(file,after);const b=await mutateDocument(other,{kind:'blueprint',id:'hut',expectedRevision:revision(after),value:{id:'hut',note:'Bob later'},by:'Bob'});assert.equal(fs.existsSync(`${ctx.blueprintDir}/.agent-pending.edn`),false);const recovered=readEDN(fs.readFileSync(`${ctx.metadataDir}/changes.edn`,'utf8'));assert.equal(recovered.events.filter(e=>e.seq===pendingEvent.seq&&e.by==='Alice').length,1);await readChanges(ctx,{cursor:a.cursor});assert.equal(readDocument(ctx,'blueprint','hut').revision,b.revision);assert.equal(readDocument(ctx,'blueprint','hut').value.note,'Bob later');await readChanges(ctx);const afterRecovery=readEDN(fs.readFileSync(`${ctx.metadataDir}/changes.edn`,'utf8'));assert.equal(afterRecovery.events.filter(e=>e.seq===pendingEvent.seq&&e.by==='Alice').length,1)})
test('world-changes --raw returns bounded full event records from an explicit cursor',async t=>{const {ctx,args}=fixture(t),start=await readChanges(ctx);await add(ctx,'raw-event');let out;const req=changeOptions([...args,'--raw','--cursor',writeEDN(start.cursor)]);assert.equal(req.raw,true);const result=await changes(req,{output:async value=>{out=value}});assert.equal(result.items.length,1);assert.equal(out.items[0].id,'raw-event');assert.equal(out.items[0].source.key,'intent');assert.equal(out.items[0].revision,readDocument(ctx,'marker','raw-event').revision)})
test('recovery refuses overwriting unrelated external edits; change limits cannot stall a cursor',async t=>{const {ctx}=fixture(t);const a=await add(ctx,'a'),d=readDocument(ctx,'marker','a'),before=fs.readFileSync(d.path,'utf8'),ledger=readEDN(fs.readFileSync(`${ctx.metadataDir}/changes.edn`,'utf8'));fs.writeFileSync(`${ctx.metadataDir}/pending.edn`,writeEDN({file:d.path,kind:'marker',id:'a',before:revision(before),after:JSON.stringify([marker('a',1)]),ledger}));fs.writeFileSync(d.path,JSON.stringify([marker('a',99)]));await assert.rejects(readChanges(ctx),{reason:'recovery-conflict'});assert.equal(JSON.parse(fs.readFileSync(d.path))[0].x,99);fs.unlinkSync(`${ctx.metadataDir}/pending.edn`);for(const limit of [0,-1,101,NaN])await assert.rejects(readChanges(ctx,{cursor:a.cursor,limit}),{reason:'invalid-page'})})
test('concurrent processes reclaim a dead global lock once and serialize complete map writes',async t=>{const {ctx,args}=fixture(t);fs.writeFileSync(`${ctx.blueprintDir}/.agent-transactions.lock`,'2147483647\nold');const children=Array.from({length:4},(_,i)=>new Promise((resolve,reject)=>{const child=spawn('node',[`${root}/engine/tools/map.mjs`,...args,'add','marker',`m${i}`,'--by','Alice','--data',`{:x ${i} :y 64 :z 0}`]);let out='',err='';child.stdout.on('data',c=>out+=c);child.stderr.on('data',c=>err+=c);child.on('error',reject);child.on('exit',code=>code===0?resolve(readEDN(out)):reject(Error(out+err)))}));await Promise.all(children);assert.equal(listDocuments(ctx,'marker').length,4);assert.equal(fs.existsSync(`${ctx.blueprintDir}/.agent-transactions.lock`),false);assert.equal(fs.existsSync(`${ctx.blueprintDir}/.agent-transactions.lock.reaper`),false)})

test('legacy EDN set order preserves collection revisions across reads and edits',async t=>{
  const {ctx}=fixture(t)
  const zone={name:'ordered',by:'Alice',min:[0,60,0],max:[3,70,3],allow:{set:[k('place'),k('trade'),k('harvest'),k('mine'),k('walk')]}}
  fs.writeFileSync(`${ctx.worldDir}/zones.edn`,writeEDN([zone]))
  const before=readDocument(ctx,'zone','ordered')
  assert.equal(before.revision,revision(writeEDN(zone)))
  assert.deepEqual(before.value.allow,zone.allow)
  const value={...before.value,note:'edited'}
  const result=await mutateDocument(ctx,{kind:'zone',id:'ordered',expectedRevision:before.revision,value,by:'Alice'})
  const after=readDocument(ctx,'zone','ordered')
  assert.equal(after.revision,result.revision)
  assert.equal(after.revision,revision(writeEDN(value)))
  assert.deepEqual(after.value.allow,zone.allow)
})

test('legacy marker JSON keys with slashes survive unrelated collection rewrites',async t=>{
  const {ctx}=fixture(t)
  const original={...marker('legacy'), 'extension/key':{nested:{'minecraft/stone':{value:'kept'},'namespace/flag':true}},structure:{legend:{'palette/stone':'stone'}}}
  fs.writeFileSync(`${ctx.worldDir}/places.json`,JSON.stringify([original]))
  const before=readDocument(ctx,'marker','legacy')
  assert.deepEqual(before.value,original)
  assert.equal(before.revision,revision(JSON.stringify(original)))
  await add(ctx,'unrelated')
  assert.deepEqual(JSON.parse(fs.readFileSync(`${ctx.worldDir}/places.json`,'utf8'))[0],original)
  assert.deepEqual(readDocument(ctx,'marker','legacy').value,original)
})
