(ns jobs.lib.escape
  "Reads for a body that cannot walk to its goal from where it stands, so jobs.movement.go-to can pick how to make a
  way (its escalation):
  - pit-depth: how many levels up from the feet are walled on at least three sides.
  - door: the cells of a thin wall straight ahead with a floor beyond it (jobs.access.clear-path digs them).
  - stair-heading: a heading with a solid block in front to stair up on (jobs.access.stair).
  - wall-spot: the nearest cell beside a wall, for a body in a hollow with no wall next to it.
  - natural?: whether a block is natural terrain; with the blocks the body placed itself, the only ones an escalation digs.
  - stair-cuts: the cells a stair up cuts.
  - door-beside?: whether a door or gate borders the cells the body can walk to (a way out go-to handles).
  - choose: the escalation for a body here and a goal.
  Cells are [x y z]. block-at maps a cell to its block name (nil when not loaded)."
  (:require [jobs.lib.access.rules :as rules]
            [jobs.lib.reach :as reach]
            [jobs.lib.shelter :as sh]
            [jobs.lib.util :as u]))

(def max-depth 8)

(def wall-search-radius
  "How far (blocks along x and along z) wall-spot looks."
  24)

(def cardinals [[1 0] [-1 0] [0 1] [0 -1]])

(def heading-names {[1 0] :east [-1 0] :west [0 1] :south [0 -1] :north})

(def pillar-items
  "Blocks worth pillaring with, most common first. No sand or gravel: they fall."
  ["dirt" "cobblestone" "cobbled_deepslate" "stone" "deepslate" "netherrack" "andesite" "diorite" "granite"
   "oak_planks" "spruce_planks" "birch_planks"])

(def protected
  "Blocks a way out never digs: doors, gates, trapdoors, beds, containers, signs, and what cannot be broken."
  #"_door$|_gate$|_trapdoor$|_bed$|chest$|barrel$|shulker_box$|furnace$|^smoker$|^hopper$|^dispenser$|^dropper$|^brewing_stand$|^lectern$|_sign$|^spawner$|^bedrock$|^barrier$|portal|^command_block$|^structure_block$|^jigsaw$")

(def natural-blocks
  "Natural terrain: generated by worldgen and rarely built with. An escalation digs only these and what the body placed
  itself (its own put-back blocks). Anything else (planks, logs, bricks, glass, wool, cobblestone, glowstone, fences,
  doors ...) may be someone's build and is never dug."
  #"^(?:stone|deepslate|andesite|diorite|granite|tuff|calcite|dirt|coarse_dirt|rooted_dirt|grass_block|podzol|mycelium|mud|clay|sand|red_sand|gravel|sandstone|red_sandstone|terracotta|(?:white|orange|magenta|light_blue|yellow|lime|pink|gray|light_gray|cyan|purple|blue|brown|green|red|black)_terracotta|netherrack|soul_sand|soul_soil|basalt|smooth_basalt|blackstone|end_stone|moss_block|dripstone_block|snow_block|snow|[a-z_]+_ore|[a-z_]+_leaves|mangrove_roots|ice|packed_ice|blue_ice|powder_snow|magma_block|pointed_dripstone|amethyst_block|budding_amethyst|suspicious_sand|suspicious_gravel|crimson_nylium|warped_nylium|nether_wart_block|warped_wart_block|ancient_debris|bone_block|sculk|infested_[a-z_]+)$")

(defn natural? [n] (boolean (and n (re-find natural-blocks n))))

(defn block-at-of
  "block-at over primitives p."
  [p]
  (fn [[x y z]] (u/block-name p {:x x :y y :z z})))

(defn add [[x y z] [dx dy dz]] [(+ x dx) (+ y dy) (+ z dz)])

(defn up [cell n] (add cell [0 n 0]))

(defn ahead [cell [dx dz] k] (add cell [(* k dx) 0 (* k dz)]))

(defn solid?
  "A loaded block that is neither air, a fluid nor a plant a body walks through."
  [n]
  (boolean (and n (not (rules/replaceable n)) (not (rules/fluids n)))))

(defn passable? [n] (boolean (and n (rules/replaceable n) (not (rules/fluids n)))))

(defn protected? [n] (boolean (and n (re-find protected n))))

(defn heading
  "Unit step [dx dz] along the larger horizontal axis from cell a toward cell b, or nil when b is straight above or
  below."
  [[ax _ az] [bx _ bz]]
  (let [dx (- bx ax) dz (- bz az)]
    (cond
      (and (zero? dx) (zero? dz)) nil
      (>= (js/Math.abs dx) (js/Math.abs dz)) [(js/Math.sign dx) 0]
      :else [0 (js/Math.sign dz)])))

(defn walled-at?
  "At least three of the four sides of cell are solid."
  [block-at cell]
  (>= (count (filter #(solid? (block-at (ahead cell % 1))) cardinals)) 3))

(defn pit-depth
  "Levels up from the feet, 0, 1, ..., walled on at least three sides, at most max-depth."
  [block-at feet]
  (count (take-while #(walled-at? block-at (up feet %)) (range max-depth))))

(defn stair-cuts
  "The cells a stair up along dir ([dx dz]) cuts from feet in n steps, step by step (jobs.access.stair/step-cells)."
  [feet [dx dz] n]
  (vec (for [i (range n)
             :let [f (add feet [(* i dx) i (* i dz)])
                   nxt (add f [dx 1 dz])]
             cell [(up f 2) (up nxt 1) nxt]]
         cell)))

(def usable-door #"^(?!iron_door$)[a-z_]+_door$|_fence_gate$")

(def door-block #"_door$|_fence_gate$|_trapdoor$")

(defn enclosed?
  "reach/enclosed?, with every door, gate and trapdoor a wall when doors is :never (the walk will not open them)."
  [p doors]
  (if (not= :never doors)
    (reach/enclosed? p)
    (let [base (reach/lookup p reach/body-kind-of)
          block-at (block-at-of p)
          kind-at (fn [x y z] (if (some->> (block-at [x y z]) (re-find door-block)) :solid (base x y z)))
          {:keys [x y z]} (reach/standing-cell p base)]
      (= :closed (reach/flood (partial reach/forward kind-at) [x y z] reach/room-cells)))))

(defn open-door-beside?
  "door-beside? without the :doors check."
  [p [fx fy fz]]
  (let [kind-at (reach/lookup p reach/body-kind-of)
        block-at (block-at-of p)
        door? (fn [[x y z]] (some (fn [[dx dz]] (some #(some->> (block-at [(+ x dx) (+ y %) (+ z dz)]) (re-find usable-door))
                                                     [0 1]))
                                  cardinals))]
    (loop [queue #queue [[fx fy fz]] seen #{[fx fy fz]}]
      (if-let [cell (peek queue)]
        (if (door? cell)
          true
          (let [nbrs (->> (apply reach/forward kind-at cell) (map vec) (remove seen))]
            (if (>= (count seen) reach/room-cells)
              false
              (recur (into (pop queue) nbrs) (into seen nbrs)))))
        false))))

(defn door-beside?
  "Whether a door or gate the body can open is beside, at feet or head height, a cell the body can walk to from feet
  (jobs.lib.reach/forward, at most reach/room-cells cells): the body's enclosure has a way out go-to opens or a
  player would, never one to dig round. Iron doors are walls, and so is every door when doors is :never."
  ([p feet] (door-beside? p feet :shut))
  ([p [fx fy fz] doors]
   (and (not= :never doors) (open-door-beside? p [fx fy fz]))))


(defn walled-side? [block-at cell] (boolean (some #(solid? (block-at (ahead cell % 1))) cardinals)))

(defn door
  "A door through a wall straight ahead of feet along dir: {:cells [...] :through cell}, the wall's solid cells at feet
  and head height (head first, row by row) and the first cell beyond with room for the body and a floor. nil when
  the cell in front is open, the wall is thicker than max-thick, a row has no floor, or a cell is protected."
  [block-at feet dir max-thick]
  (loop [k 1 cells []]
    (let [row (ahead feet dir k)
          pair [(up row 1) row]
          names (map block-at pair)]
      (cond
        (not (rules/solid-floor? block-at (up row -1))) nil
        (some nil? names) nil
        (every? passable? names) (when (> k 1) {:cells cells :through row})
        (> k max-thick) nil
        (some protected? names) nil
        (some rules/fluids names) nil
        :else (recur (inc k) (into cells (filter #(solid? (block-at %)) pair)))))))

(defn diggable?
  "Whether an escalation may cut cell: it is open (air or a plant), or natural terrain or a block the body placed
  itself (own?: (own? cell block)) that may-dig? allows."
  ([block-at may-dig? cell] (diggable? block-at may-dig? (constantly false) cell))
  ([block-at may-dig? own? cell]
   (let [n (block-at cell)]
     (or (passable? n) (and (or (natural? n) (boolean (and n (own? cell n)))) (boolean (may-dig? cell)))))))

(defn stair-heading
  "The first heading of dirs (each [dx dz]) with a solid block in front at feet height to stand on and every cell of
  the n steps' cuts diggable? (natural terrain, may-dig?), as a keyword (:east ...), or nil."
  ([block-at feet dirs] (stair-heading block-at feet dirs 1 (constantly true)))
  ([block-at feet dirs n may-dig?] (stair-heading block-at feet dirs n may-dig? (constantly false)))
  ([block-at feet dirs n may-dig? own?]
   (some (fn [d]
           (let [front (ahead feet d 1)]
             (when (and (solid? (block-at front)) (not (protected? (block-at front)))
                        (every? #(diggable? block-at may-dig? own? %) (stair-cuts feet d (max 1 n))))
               (heading-names d))))
         dirs)))

(defn wall-spot
  "The nearest cell (breadth-first through standable cells, at most wall-search-radius away along x and z) that has
  a solid side: one whose side along dir is solid when there is one, else the first with any. nil when none."
  [p feet dir]
  (let [block-at (block-at-of p)
        [hx _ hz] feet
        near? (fn [[x _ z]] (and (<= (js/Math.abs (- x hx)) wall-search-radius)
                                 (<= (js/Math.abs (- z hz)) wall-search-radius)))
        standable? (fn [[x y z]] (reach/standable-cell? p {:x x :y y :z z}))
        dirs (distinct (cond->> cardinals dir (cons dir)))]
    (loop [queue #queue [feet] seen #{feet} fallback nil]
      (if-let [cell (peek queue)]
        (let [here? (= cell feet)]
          (if (and dir (not here?) (solid? (block-at (ahead cell dir 1))))
            cell
            (let [fallback (or fallback (when (and (not here?) (walled-side? block-at cell)) cell))
                  nbrs (->> dirs (map #(ahead cell % 1)) (filter #(and (not (seen %)) (near? %) (standable? %))))]
              (recur (into (pop queue) nbrs) (into seen nbrs) fallback))))
        fallback))))

(defn pillar-item
  "{:item :count}: the carried pillar block with the largest count, or nil."
  [p]
  (let [have (->> (u/inventory p)
                  (filter #(some #{(:name %)} pillar-items))
                  (reduce (fn [m {:keys [name count]}] (update m name (fnil + 0) count)) {}))]
    (when (seq have)
      (let [[item n] (apply max-key val have)] {:item item :count n}))))

(def max-door 3)

(defn door-spot
  "The nearest cell (breadth-first through standable cells, within wall-search-radius) other than feet from which a
  wall straight along dir is a door (door) whose every cell is diggable?: where to walk when the wall at feet cannot be
  dug (an iron door or another's build in line). nil when none."
  [p feet dir diggable]
  (let [block-at (block-at-of p)
        [hx _ hz] feet
        near? (fn [[x _ z]] (and (<= (js/Math.abs (- x hx)) wall-search-radius)
                                 (<= (js/Math.abs (- z hz)) wall-search-radius)))
        standable? (fn [[x y z]] (reach/standable-cell? p {:x x :y y :z z}))
        ok? (fn [cell] (when-let [gap (door block-at cell dir max-door)] (every? diggable (:cells gap))))]
    (loop [queue #queue [feet] seen #{feet}]
      (when-let [cell (peek queue)]
        (if (and (not= cell feet) (ok? cell))
          cell
          (let [nbrs (->> cardinals (map #(ahead cell % 1)) (filter #(and (not (seen %)) (near? %) (standable? %))))]
            (recur (into (pop queue) nbrs) (into seen nbrs))))))))

(def heading-dirs (into {} (map (fn [[k v]] [v k])) heading-names))

(defn choose
  "How a body at feet (a cell) that cannot walk to goal (a cell) can make a way, cheapest first. It only ever digs
  natural terrain (natural?) and blocks it placed itself (opts :own?, (own? cell block)) in cells (may-dig? cell)
  allows (go-to: no other owner's zone or claim). opts :skip is a set of steps that already failed (a stair heading
  that failed: [:stair :east]): the next one is chosen.
  - {:step :pillar :height d :item}: in a pit d deep with room above the head and at least d pillar blocks carried.
  - {:step :stair :heading kw :steps n}: a block in front to stair up on, n the pit's depth (in no pit: how far the
    goal is above, at most max-depth), every cell of its cut diggable?.
  - {:step :clear-path :heading kw}: a wall at most max-door thick straight toward the goal, with floor beyond,
    every cell diggable?.
  - {:step :approach :pos cell}: no side of the body's cell is solid: walk to wall-spot first.
  - {:step :none :why kw}: none of these. :why :no-headroom: a pit the carried blocks would pillar out of but for
    the block over the head; :no-dig: nothing natural and allowed to dig; :no-wall: no wall to walk to."
  ([p feet goal] (choose p feet goal (constantly true)))
  ([p feet goal may-dig?] (choose p feet goal may-dig? nil))
  ([p feet goal may-dig? {:keys [own? skip] :or {own? (constantly false) skip #{}}}]
   (let [block-at (block-at-of p)
         dir (heading feet goal)
         depth (pit-depth block-at feet)
         {:keys [item count]} (pillar-item p)
         pillar-blocks? (and (not (skip :pillar)) (pos? depth) item (>= count depth))
         rise (if (pos? depth) depth (min max-depth (max 0 (- (second goal) (second feet)))))
         stair (when (and (not (skip :stair)) (pos? rise))
                 (stair-heading block-at feet
                                (remove #(skip [:stair (heading-names %)]) (distinct (cond->> cardinals dir (cons dir))))
                                rise may-dig? own?))
         gap (when (and dir (not (skip :clear-path))) (door block-at feet dir max-door))]
     (cond
       (and pillar-blocks? (passable? (block-at (up feet 2))))
       {:step :pillar :height depth :item item}

       stair
       {:step :stair :heading stair :steps rise}

       (and gap (every? #(diggable? block-at may-dig? own? %) (:cells gap)))
       {:step :clear-path :heading (heading-names dir)}

       (and dir (not (skip :approach)) (walled-side? block-at feet)
            (door-spot p feet dir #(diggable? block-at may-dig? own? %)))
       {:step :approach :pos (door-spot p feet dir #(diggable? block-at may-dig? own? %))}

       (and (not (skip :approach)) (not (walled-side? block-at feet)))
       (if-let [spot (wall-spot p feet dir)] {:step :approach :pos spot} {:step :none :why :no-wall})

       pillar-blocks? {:step :none :why :no-headroom}

       :else {:step :none :why :no-dig}))))
