(ns dashboard.routes-test
  (:require [cljs.test :refer [deftest is testing]]
            [dashboard.routes :as routes]))

(deftest route-cases
  (doseq [[url expected]
          [["/" {:kind :page}]
           ["/index.html" {:kind :page}]
           ["/villagers" {:kind :page}]
           ["/villages?place=market" {:kind :page}]
           ["/blueprints" {:kind :page}]
           ["/api/worlds" {:kind :worlds}]
           ["/api/state" {:kind :state}]
           ["/api/state?since=3" {:kind :state}]
           ["/api/villagers" {:kind :villagers-api}]
           ["/api/villages" {:kind :villages-api}]
           ["/api/chat" {:kind :chat}]
           ["/api/chat?limit=50" {:kind :chat}]
           ["/api/chat/" {:kind :unknown}]
           ["/api/world?place=jizo-cane" {:kind :world}]
           ["/api/world/jizo-cane" {:kind :unknown}]
           ["/api/blueprints" {:kind :blueprints}]
           ["/api/blueprint-preview" {:kind :blueprint-preview}]
           ["/api/blueprint/starter-hut" {:kind :blueprint :name "starter-hut"}]
           ["/api/blueprint/Starter_Hut" {:kind :unknown}]
           ["/api/blueprint/" {:kind :unknown}]
           ["/api/blueprint/../etc" {:kind :unknown}]
           ["/api/look/Chani" {:kind :unsupported}]
           ["/api/look/Chani/live" {:kind :unsupported}]
           ["/api/screen/Chani" {:kind :unsupported}]
           ["/api/actions/Chani" {:kind :unsupported}]
           ["/api/whisper/Chani" {:kind :unsupported}]
           ["/api/icon/oak_log" {:kind :unsupported}]
           ["/api/look/" {:kind :unknown}]
           ["/map" {:kind :page}]
           ["/plans" {:kind :page}]
           ["/jobs" {:kind :page}]
           ["/api/thumb/Chani.png" {:kind :thumb :name "Chani"}]
           ["/api/thumb/Probe_Walk-2.png?v=123" {:kind :thumb :name "Probe_Walk-2"}]
           ["/api/thumb/Chani" {:kind :unknown}]
           ["/api/thumb/.png" {:kind :unknown}]
           ["/api/thumb/../x.png" {:kind :unknown}]
           ["/api/thumb/a b.png" {:kind :unknown}]
           ["/api/thumbs/stats" {:kind :thumbs-stats}]
           ["/js/main.js" {:kind :static :path "/js/main.js"}]
           ["/app.css" {:kind :static :path "/app.css"}]
           ["/js/../../etc/passwd" {:kind :unknown}]
           ["/nope" {:kind :unknown}]]]
    (testing url
      (is (= expected (routes/route url))))))
