(ns dashboard.routes-test
  (:require [cljs.test :refer [deftest is testing]]
            [dashboard.routes :as routes]))

(deftest route-cases
  (doseq [[url expected]
          [["/" {:kind :page}]
           ["/index.html" {:kind :page}]
           ["/villagers" {:kind :page}]
           ["/villages?place=market" {:kind :page}]
           ["/blueprints" {:kind :page}]
           ["/api/worlds" {:kind :worlds}]
           ["/api/state" {:kind :state}]
           ["/api/state?since=3" {:kind :state}]
           ["/api/villagers" {:kind :villagers-api}]
           ["/api/villages" {:kind :villages-api}]
           ["/api/chat" {:kind :chat}]
           ["/api/chat?limit=50" {:kind :chat}]
           ["/api/chat/" {:kind :unknown}]
           ["/api/restart" {:kind :restart}]
           ["/api/world?place=jizo-cane" {:kind :world}]
           ["/api/world/jizo-cane" {:kind :unknown}]
           ["/api/blueprints" {:kind :blueprints}]
           ["/api/blueprint-preview" {:kind :blueprint-preview}]
           ["/api/tile/claude/1.-6.png" {:kind :tile :world "claude" :cx 1 :cz -6}]
           ["/api/tile/claude/-12.340.png?m=5" {:kind :tile :world "claude" :cx -12 :cz 340}]
           ["/api/tile/claude/1.-6.jpg" {:kind :unknown}]
           ["/api/tile/claude/../1.2.png" {:kind :unknown}]
           ["/api/tile/1.2.png" {:kind :unknown}]
           ["/api/tiles/claude" {:kind :tiles :world "claude"}]
           ["/api/tiles/claude?since=5" {:kind :tiles :world "claude"}]
           ["/api/tiles/" {:kind :unknown}]
           ["/api/blueprint/starter-hut" {:kind :blueprint :name "starter-hut"}]
           ["/api/blueprint/Starter_Hut" {:kind :unknown}]
           ["/api/blueprint/" {:kind :unknown}]
           ["/api/blueprint/../etc" {:kind :unknown}]
           ["/api/look/Chani" {:kind :unsupported}]
           ["/api/look/Chani/live" {:kind :unsupported}]
           ["/api/screen/Chani" {:kind :unsupported}]
           ["/api/actions/Chani" {:kind :unsupported}]
           ["/api/whisper/claude/Chani" {:kind :whisper-send :world "claude" :name "Chani"}]
           ["/api/whisper/Chani" {:kind :unknown}]
           ["/api/whisper/" {:kind :unknown}]
           ["/api/icon/oak_log" {:kind :unsupported}]
           ["/api/look/" {:kind :unknown}]
           ["/map" {:kind :page}]
           ["/plans" {:kind :page}]
           ["/api/plans?world=claude" {:kind :plans-api}]
           ["/api/plan/chani-wheat-field?world=claude" {:kind :plan-api :name "chani-wheat-field"}]
           ["/api/plan/" {:kind :unknown}]
           ["/api/plan/a/b" {:kind :unknown}]
           ["/api/plan/..%2Fx" {:kind :unknown}]
           ["/jobs" {:kind :page}]
           ["/api/jobs" {:kind :jobs-api}]
           ["/api/jobs/x" {:kind :unknown}]
           ["/api/chat/send" {:kind :chat-send}]
           ["/api/chat/send/" {:kind :unknown}]
           ["/api/thumb/claude/Chani.png" {:kind :thumb :world "claude" :name "Chani"}]
           ["/api/thumb/Chani.png" {:kind :unknown}]
           ["/api/thumb/w_2/Probe_Walk-2.png?v=123" {:kind :thumb :world "w_2" :name "Probe_Walk-2"}]
           ["/api/thumb/claude/Chani" {:kind :unknown}]
           ["/api/thumb/.png" {:kind :unknown}]
           ["/api/thumb/../x.png" {:kind :unknown}]
           ["/api/thumb/claude/../x.png" {:kind :unknown}]
           ["/api/thumb/a b.png" {:kind :unknown}]
           ["/api/thumbs/stats" {:kind :thumbs-stats}]
           ["/js/main.js" {:kind :static :path "/js/main.js"}]
           ["/app.css" {:kind :static :path "/app.css"}]
           ["/js/../../etc/passwd" {:kind :unknown}]
           ["/nope" {:kind :unknown}]]]
    (testing url
      (is (= expected (routes/route url))))))

(deftest detail-routes
  (doseq [[url expected]
          [["/api/item-icon/bread.png" {:kind :item-icon :name "bread"}]
           ["/api/item-icon/oak_log.png" {:kind :item-icon :name "oak_log"}]
           ["/api/item-icon/Bread.png" {:kind :unknown}]
           ["/api/item-icon/../x.png" {:kind :unknown}]
           ["/api/events/claude/ProbeMove?limit=300" {:kind :events :world "claude" :name "ProbeMove"}]
           ["/api/events/claude/Probe-Move_2" {:kind :events :world "claude" :name "Probe-Move_2"}]
           ["/api/events/ProbeMove" {:kind :unknown}]
           ["/api/attention/claude/ProbeMove/resolve" {:kind :attention-resolve :world "claude" :name "ProbeMove"}]
           ["/api/attention/ProbeMove/resolve" {:kind :unknown}]
           ["/api/attention/w/Probe-Move_2/resolve" {:kind :attention-resolve :world "w" :name "Probe-Move_2"}]
           ["/api/attention/../resolve" {:kind :unknown}]
           ["/api/events/" {:kind :unknown}]
           ["/api/events/a/b/c" {:kind :unknown}]
           ["/api/events/w/..%2Fx" {:kind :unknown}]]]
    (is (= expected (routes/route url)) url)))
